name: build-deploy-docker-woodland
on:
  workflow_dispatch:

jobs:
  build-deploy-docker-woodland:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on local server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST_WOODLAND }}
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          #key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |
            cd ~/my_docker/astroview
            git pull
            npm install --openssl-legacy-provider
            npm audit fix
            npm run build --openssl-legacy-provider
            docker build -t astroview:latest .
            
            # deploy with docker-compose
            cd $HOME/shared
            docker stop astroview
            docker rm -f astroview
            docker compose -p astronest -f ~/shared/docker-compose-astro.yml up -d
