name: build-deploy-astroview
on: [push]
jobs:
  build-astroview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install node packages
        run: npm install
      - name: build astroview
        run: npm run build
        env:
           CI: ""

      - name: scp files to uilennest
        uses: appleboy/scp-action@master
        with:
          host: "uilennest.net"
          port: 22
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          rm: true
          source: "build/"
          target: ${{ secrets.MY_REMOTE_DIR }}