name: build-deploy-astroview
on: [push]
jobs:
  build-astroview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install node packages
        run: npm install
      - name: build astroview
        run: npm run build
        env:
           CI: ""

      - name: scp files to webserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          rm: true
          source: "build/index.html,favicon.ico,static/"
          target: "www/astroview-ci/index.html,www/astroview-ci/favicon.ico,www/astroview-ci/static/"

#      - name: scp static files to webserver
#        uses: sand4rt/ftp-deployer@v1.1
#        with:
#          host: ${{ secrets.MY_HOST }}
#          port: 22
#          username: ${{ secrets.MY_USER }}
#          password: ${{ secrets.MY_PASSWORD }}
#          cleanup: true
#          local_folder: "build/static"
#          remote_folder: "www/astroview-ci"
