name: build-deploy-astroview
on: [push]
jobs:
  build-astroview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: build
          run: npm run build
          env:
            CI: ""
