# this is the old mechanism where the frontend application is built with npm
# and then moved to a central ~/www web directory that is served by Apache2.
# This mechanism is replaced with deployment in Docker, but I leave this in place in case it is needed again.
name: build-deploy-astroview
on:
  push:
    branches:
      - master-temporary-disabled

jobs:
  build-deploy-astroview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v2

      - name: install node packages
        run: npm install
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: build astroview
        run: npm run build
        env:
           CI: ""
           NODE_OPTIONS: "--openssl-legacy-provider"

      - name: upload files to webserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          rm: true
          source: "build"
          target: "~/www/repository/astroview"

      - name: move files to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          script: |
             cd ~/www/astroview
             cp ~/www/repository/astroview/build/*.* .
             cp -r ~/www/repository/astroview/build/static/* ~/www/my_static_files